# Generated by Django 4.1.3 on 2022-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('thumbnail', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
