# Generated by Django 4.1.3 on 2022-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_deal',
            field=models.BooleanField(null=True),
        ),
    ]
