# Generated by Django 4.1.3 on 2022-11-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='product',
            new_name='product_id',
        ),
    ]
