# Generated by Django 4.1.3 on 2022-11-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_rename_product_transaction_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flash_deal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
