# Generated by Django 4.1.3 on 2022-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time_released',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
